Fix: ece-deploy now can handle publication name or file path with space
escenic/ece-scripts pull request #51
Opened 2018-08-07 11:41 UTC by modhassan

remember_state use default internal field separator (IFS)
which split word by space
If there any publication name or file path contains space
then it split the file path incorrectly
which cause cause error like 'No such file or directory'

Used custom internal field separator IFS=$'\n'

2018-08-07 14:56 UTC, skybert commented on usr/sbin/ece-deploy
>    dpkg -L vosa-conf-$HOSTNAME | while read f; do
Just to be clear: you've got files in the `vosa-conf` DEB package that contain spaces?

Are you sure the default `IFS` breaks the iteration from the output of `dpkg -L`? AFAICT, each file comes on its own line (with the default IFS):
```
  l="/tmp/hello world.txt
/tmp/there world.txt
"

  echo "${l}" | while read file; do
    echo file=$file
  done
```

2018-08-07 14:58 UTC, skybert requested changes

2018-08-07 14:58 UTC, skybert commented on usr/sbin/ece-deploy
>      cp $f $dir/
I would guess that the real problem is this line here. The `cp` will fail if `$f` contains a space. 

A fix for this would be (hardening `$dir` at the same time):
```
cp "${f}" "${dir}/"
```

2018-08-08 03:43 UTC, modhassan commented on usr/sbin/ece-deploy
>    dpkg -L vosa-conf-$HOSTNAME | while read f; do
Hands up. I misunderstood.
Now I found the actual cause.
``` 
$ dirname /tmp/hello/test world.txt
/tmp/hello
.
```

2018-08-08 03:48 UTC, modhassan commented on usr/sbin/ece-deploy
>    dpkg -L vosa-conf-$HOSTNAME | while read f; do
`local dir=${1}/vosa-conf-${HOSTNAME}/$(dirname $f)` --> `local dir=${1}/vosa-conf-${HOSTNAME}/$(dirname "$f")`
could be the fix.

2018-08-08 06:57 UTC, skybert commented on usr/sbin/ece-deploy
>    dpkg -L vosa-conf-$HOSTNAME | while read f; do
This should work:
```
make_dir "/tmp/etc/escenic/engine/webapp/test website"
```

2018-08-08 07:06 UTC, modhassan commented on usr/sbin/ece-deploy
>    dpkg -L vosa-conf-$HOSTNAME | while read f; do
Did not worked for me
```
$ cat test2.sh 
#!/bin/bash

function make_dir() {
for el in $@; do
  if [ ! -d $el ]; then
     mkdir -p $el
  fi
done
}
make_dir "/tmp/etc/escenic/engine/webapp/test website"
ls -al "/tmp/etc/escenic/engine/webapp/test website"
```
```
$ ./test2.sh 
ls: cannot access '/tmp/etc/escenic/engine/webapp/test website': No such file or directory
```

2018-08-08 07:40 UTC, skybert commented on usr/sbin/ece-deploy
>    dpkg -L vosa-conf-$HOSTNAME | while read f; do
Try this:
```
function make_dir() {
  while read -r el; do
    mkdir -p "${el}"
  done <<< "${@}"
}
```

I urge you to create `ece-scripts/usr/local/src/unit-tests/common-io-test.sh` (just like `common-ece-test.sh` and write tests to prove that both directories with and without spaces work. The fix goes in `common-io.sh` of course.

2018-08-08 10:54 UTC, modhassan commented
@skybert changes are done accordingly
Now we are not using custom field separator anymore.

2018-08-08 11:39 UTC, skybert requested changes
The fix and tests look good, @modhassan .

Please squash the three commits into one as these are really one change.

2018-08-14 03:14 UTC, modhassan commented
squash is done @skybert

2018-08-14 08:22 UTC, skybert approved these changes

2018-08-15 18:14 UTC, merged