New Docker friendly command: ece run
escenic/ece-scripts pull request #56
Opened 2018-09-13 09:11 UTC by skybert

- runs the app server in the foreground.

- runs the app server in the foreground.This is especially useful when
  running ECE & search instances in a Docker container were the
  container process is expected to run in the foreground outputting
  its standard log file to standard out.

- Some developers may prefer 'ece run' over 'ece start' too, as it'll
  give them 'Ctrl + c' to stop the app server(s).

2018-09-24 13:31 UTC, mhersson approved these changes
Looks good

2018-09-24 17:30 UTC, mogsie requested changes
Great! Good to avoid the hack I have in my Dockerfiles.

2018-09-24 17:30 UTC, mogsie commented on usr/share/escenic/ece-scripts/ece.d/start.sh
> +        $tomcat_home/bin/catalina.sh run
I think you want to (if possible) _exec_ to this process, in the hopes that catalina.sh again chains to the java process, so that e.g. kill / quit signals target the correct process when docker wants to kill the proces.

2018-09-25 06:09 UTC, modhassan approved these changes
Excited to have this feature!!!
Looks okay to me though could not test yet.

2018-09-28 09:07 UTC, skybert commented on usr/share/escenic/ece-scripts/ece.d/start.sh
> +        $tomcat_home/bin/catalina.sh run
Added `exec` in 379399c30821e9a8a2dd512c4cecf39158bd8d14.

- Confirmed that it forks off the java process so that `ece run` is no longer listed as a running process once the `exec ...` is executed.
- Confirmed that killing the java process terminates the execution of `ece run` too.
- Confirmed that `C-c` in the shell where `ece run` terminates the Java process.

2018-09-28 14:22 UTC, mogsie approved these changes

2018-10-01 07:11 UTC, merged