VOSA-530 'npm run dist' creates zip archives of all packages
escenic/ece-scripts pull request #73
Opened 2019-02-06 14:58 UTC by skybert

-` npm run dist` creates DEBs and RPMs of all defined packages (as
  returned by create-packages -l) and make zip archives out of these.
  These zip archives are compatible with the Escenic release process.

- the produced zip archives are copied to the dist directory on the root
  (git ignored).

- Example run:

```
$ npm run dist
> ece-scripts@5.0.0-SNAPSHOT predist /home/torstein/src/ece-scripts
> mkdir -p dist

> ece-scripts@5.0.0-SNAPSHOT dist /home/torstein/src/ece-scripts
> ./usr/share/escenic/package-scripts/create-zip-archives

/tmp/escenic-build-scripts-5.0.0-SNAPSHOT.zip
/tmp/escenic-check-mk-plugins-5.0.0-SNAPSHOT.zip
/tmp/escenic-check-mk-server-plugins-5.0.0-SNAPSHOT.zip
/tmp/escenic-common-scripts-5.0.0-SNAPSHOT.zip
/tmp/escenic-content-engine-installer-5.0.0-SNAPSHOT.zip
/tmp/escenic-content-engine-scripts-5.0.0-SNAPSHOT.zip
/tmp/escenic-munin-plugins-5.0.0-SNAPSHOT.zip
/tmp/hugin-node-5.0.0-SNAPSHOT.zip
/tmp/spore-5.0.0-SNAPSHOT.zip
/tmp/vosa-5.0.0-SNAPSHOT.zip

> ece-scripts@5.0.0-SNAPSHOT postdist /home/torstein/src/ece-scripts
> cp /tmp/*-${npm_package_version}.zip dist/
```

2019-02-07 12:29 UTC, modhassan approved these changes

2019-02-07 13:28 UTC, mogsie reviewed
Please to not write to files outside the project's own directory, since it'll just lead to permissions errors down the road.

2019-02-07 13:28 UTC, mogsie commented on package.json
> +    "postdist": "cp /tmp/*-${npm_package_version}.zip dist/"
I'm not so happy with using a shared directory for this.  It's relatively OK since we don't create a directory, because that would cause a lot of permission errors.  But wouldn't it be easier if we could pass `$PWD/dist/` to the create-zip-archives command instead?

2019-02-07 13:29 UTC, mogsie requested changes
I meant to tap "request changes" but hit Ctrl+Enter out of habit...

2019-02-07 15:36 UTC, skybert commented on package.json
> +    "postdist": "cp /tmp/*-${npm_package_version}.zip dist/"
Using `/tmp` is a relic from the `create-packages` command (2012, mate) writing the DEBs and RPMs in a date specific directory, but `create-zip-archives` could of course do the right thing :tm: .

2019-02-08 14:25 UTC, skybert commented on package.json
> +    "postdist": "cp /tmp/*-${npm_package_version}.zip dist/"
I've addressed your concerns in `86b75f2f38113bb8e729929e67ec90f340f4ea33`:

- `create-zip-archives` doesn't use a shared directory anymore
- no `postdist` anymore
- added options parsing, including `--release-version <ver>` and `--dir <dir>`, the latter of which is of interest here and is hence used in `package.json` passing on `CWD` as you suggested.

2019-02-11 12:05 UTC, mogsie approved these changes

2019-02-11 16:17 UTC, merged