Priming contentstore
escenic/ece-scripts pull request #81
Opened 2019-05-29 07:38 UTC by mogsie

This new feature is here to simplify the creation (and possibly maintenance) of a Content Store.  Together with an .ini file which describes the OUs, publication types, publications, tags, shared resources, and so on, the new `ece apply-conf` will create them all.  If something is already there, it is "refreshed", i.e. changed files are uploaded, unchanged files are left alone.

Hopefully, this can replace a lot of bespoke "create publication" and similar things left and right.

2019-05-29 09:29 UTC, skybert reviewed
Just two quick comments: 
- shouldn't some of the 25 commits be squashed? 
- there's no Jira issue key in the commits, is this intentional? (the release process now tags the Jira issues included in the `ece-scripts` release)

2019-05-29 09:58 UTC, skybert requested changes
Nice `ece` sub command. Looks good. I suggest squashing the commits that don't make sense on their own (25 is a lot!), adding a Jira issue key if one exists and adding a few unit tests for the `.ini` file parsing.

2019-05-29 09:58 UTC, skybert commented on usr/local/src/development/README.md
> +Docker environment for testing things
Nice.

2019-05-29 09:58 UTC, skybert commented on usr/share/escenic/ece-scripts/ece.d/apply-conf.sh
> +  $(basename "$0") apply-conf [<options>]
`[` implies the options are optional, is this intentional?

2019-05-29 09:58 UTC, skybert commented on usr/share/escenic/ece-scripts/ece.d/apply-conf.sh
> +  command -v xmlstarlet  >/dev/null 2>&1 || { echo "I require xmlstarlet but it's not installed.  Aborting." >&2; exit 1; }
We already have `common-os::assert_commands_available()`, you should be able to replace `_apply_conf_check_dependency` with:
```
assert_commands_available xmlstarlet curl
```

2019-05-29 09:58 UTC, skybert commented on usr/share/escenic/ece-scripts/ece.d/apply-conf.sh
> +							 name="some-editors_workspace" search-filter="some-editors-workspace">
indent on 358 & 359 look off

2019-05-29 09:58 UTC, skybert commented on usr/share/escenic/ece-scripts/ece.d/apply-conf.sh
> +    if [ $index -eq 0 ] ; then
Curious: Doesn't shellcheck warn you about `$index`?

2019-05-29 09:58 UTC, skybert commented on usr/share/escenic/ece-scripts/ece.d/apply-conf.sh
> +OU = My OU
Shouldn't `OU` be `ou` when all the other keys are small?

2019-05-29 09:58 UTC, skybert commented on usr/share/escenic/ece-scripts/ece.d/apply-conf.sh
> +  if ! ${_apply_conf_dry_run} ; then
Shellcheck ...

2019-05-29 09:58 UTC, skybert commented on usr/share/escenic/ece-scripts/ece.d/apply-conf.sh
> +      # ignore file if --no-error
Missing code below this comment or is it done in `handle_error()`?

2019-05-29 09:58 UTC, skybert commented on usr/share/escenic/ece-scripts/ece.d/apply-conf.sh
> +    set -x;
Nice

2019-05-29 09:58 UTC, skybert commented on usr/share/escenic/ece-scripts/ece.d/apply-conf.sh
> +# Given the .ini file
Consider adding some unit tests in `ece-scripts/usr/local/src/unit-tests` for this method.

2019-05-29 11:27 UTC, mogsie commented on usr/share/escenic/ece-scripts/ece.d/apply-conf.sh
> +  $(basename "$0") apply-conf [<options>]
If you don't specify options, you get the help text, which isn't an error, is it?

2019-05-29 11:28 UTC, mogsie commented on usr/share/escenic/ece-scripts/ece.d/apply-conf.sh
> +							 name="some-editors_workspace" search-filter="some-editors-workspace">
Indeed. Copy-pasted from a tab indented file.  Do the comments make sense to include in the code?

2019-05-29 11:38 UTC, mogsie commented on usr/share/escenic/ece-scripts/ece.d/apply-conf.sh
> +OU = My OU
Because it's an acronym?

2019-05-29 11:40 UTC, mogsie commented on usr/share/escenic/ece-scripts/ece.d/apply-conf.sh
> +  if ! ${_apply_conf_dry_run} ; then
My shellcheck actually doesn't complain about this.  Weird.

2019-05-29 11:44 UTC, mogsie commented on usr/share/escenic/ece-scripts/ece.d/apply-conf.sh
> +      # ignore file if --no-error
handle_error allows (with --no-error) the command to continue.  With --error, it quits.  So the code should continue on as if the error didn't happen, if handle_error ever returns.

2019-05-29 11:44 UTC, mogsie commented on usr/share/escenic/ece-scripts/ece.d/apply-conf.sh
> +    set -x;
Yeah, thanks, I avoided -x'ing my way through loads of initialization code with this. :)

2019-05-29 11:45 UTC, mogsie commented on usr/share/escenic/ece-scripts/ece.d/apply-conf.sh
> +# Given the .ini file
Yes, the original had unit-tests for this, I'll see if I can add them back.

2019-05-29 11:47 UTC, mogsie commented
I agree to squashing it all down to one commit, the commits are just noise.  I'll make a ticket too, and a nice commit message.

2019-05-29 11:55 UTC, mogsie commented on usr/local/src/development/README.md
> +Docker environment for testing things
I run `docker-compose build` and then `docker-compose run --rm ece-scripts ece apply-conf` to test my changes.

2019-05-29 11:59 UTC, mogsie commented on usr/share/escenic/ece-scripts/ece.d/apply-conf.sh
> +    if [ $index -eq 0 ] ; then
No.  statically, index can't be anything other than 0 or an integer, here, can it?  

```
$ shellcheck --version
ShellCheck - shell script analysis tool
version: 0.5.0
```

2019-05-29 11:59 UTC, mogsie commented on usr/share/escenic/ece-scripts/ece.d/apply-conf.sh
> +# Given the .ini file
I'll do that in a different PR next week.

2019-05-30 10:33 UTC, modhassan commented
@mogsie Great! to have such a nice command to manage contentstore/publication resources including OUs.
As a user of `ece apply-conf` I would love to have (If possible)
* `/escenic/plugin` publication resource support
* create publication using WAR or ZIP 
* support absolute path of resource files If possible

2019-05-31 08:54 UTC, skybert commented on usr/share/escenic/ece-scripts/ece.d/apply-conf.sh
> +  $(basename "$0") apply-conf [<options>]
I think it is. `apply-conf` doesn't work without any options. To help the user, you get the help, but it's still an error IMO. Consider:
```
❯ apt-get &>/dev/null; echo $?
1
❯ apt-get --help &>/dev/null; echo $?
0
❯ cp &> /dev/null; echo $?
1
❯ cp --help &> /dev/null; echo $?
0
```

Both `apt-get` and `cp` gives you help when you don't provide the necessary arguments, but the return code signifies error.

2019-05-31 08:54 UTC, skybert commented on usr/share/escenic/ece-scripts/ece.d/apply-conf.sh
> +    if [ $index -eq 0 ] ; then
I know it currently cannot be anything else, but I didn't know `shellcheck` was that smart :smile:

2019-05-31 09:04 UTC, skybert commented on usr/share/escenic/ece-scripts/ece.d/apply-conf.sh
> +OU = My OU
ok, then I understand. I like lower case keys better (consistent, obvious value will not be used in a UI), but that's just a matter of taste :smile:

2019-05-31 09:05 UTC, skybert approved these changes

2019-06-03 08:23 UTC, mogsie commented on usr/share/escenic/ece-scripts/ece.d/apply-conf.sh
> +OU = My OU
I agree. I'll lowercase them; actually, I'll make them case insensitive.

2019-06-03 09:21 UTC, mogsie commented on usr/share/escenic/ece-scripts/ece.d/apply-conf.sh
> +OU = My OU
All keys and section names are now case insensitive.  So

```
[ou name=foo]
...
[publication ...]
OU=foo
```

is equivalent to the following

```
[OU name=foo]
...
[Publication ...]
ou=foo
```

2019-06-03 09:23 UTC, mogsie commented on usr/share/escenic/ece-scripts/ece.d/apply-conf.sh
> +# Given the .ini file
I added tests today.

```
[run-tests.sh] Running usr/local/src/unit-tests/ece-apply-conf-test.sh ...
test_apply_conf_can_get_from_ini_file
test_apply_conf_can_get_from_ini_file_case_insensitive
test_apply_conf_can_get_from_ini_file_case_insensitive_2
test_apply_conf_can_get_from_ini_file_return_defaults
test_apply_conf_can_get_from_ini_file_return_defaults_with_whitespace
test_apply_conf_can_get_from_ini_file_with_specifier
test_apply_conf_can_get_names_of_sections
test_apply_conf_can_get_names_of_sections_with_whitespace
test_apply_conf_can_get_names_of_sections_case
test_apply_conf_can_get_keys_from_ini_file
test_apply_conf_can_get_keys_from_ini_file_case_insisitive_section
test_apply_conf_can_get_keys_from_ini_file_case_insisitive_key
test_apply_conf_can_get_keys_from_ini_file_with_specifier
test_apply_conf_can_parse_ini_file
test_apply_conf_can_parse_ini_file_with_specifier
test_apply_conf_can_parse_ini_file_with_specifier_with_whitespace
test_apply_conf_can_parse_ini_file_with_specifier_lowercasing_keys
test_apply_conf_can_parse_ini_file_with_specifier_ignoring_case_of_section_name
test_apply_conf_can_parse_ini_file_with_many_lines
test_apply_conf_can_parse_ini_file_with_many_lines

Ran 20 tests.

OK
```

2019-06-03 09:30 UTC, mogsie commented
> As a user of `ece apply-conf` I would love to have (If possible)
> 
> * `/escenic/plugin` publication resource support

Yes.  I'm thinking a ganeric way, something like this:

```
[publication name=xyzzy]

publication-resource = /escenic/plugin/menu /resources/menu.xml
publication-resource = /escenic/plugin/other /resources/my-other-plugin.properties
```

In other words a "publication-resource" key that constist of two words: the name of the publication resource, and the name of the file to be uploaded.  But I'll do that in a future PR.

> * create publication using WAR or ZIP

Yes, initially the proposal was to provide a full .zip file with the .ini + all files, but it evolved away from that.  We'll see. Maybe I could have something like this:

```
[publicaiton name=xyzzy]

war = path/to/some.war
```

the war could then be processed much like normal, picking out publication resources based on their names.

> * support absolute path of resource files If possible

There's nothing wrong with that, so I can probably add that easily.  Good idea.  Not my primary preference, but I see use cases for it.

2019-06-03 09:45 UTC, mogsie commented
@modhassan I made it possible to user absolute paths.

like:

```
[publication name=xyzzy]
content-type = /etc/content-type/*.xml
```

2019-06-03 09:49 UTC, merged

2019-06-03 09:50 UTC, mogsie commented on usr/share/escenic/ece-scripts/ece.d/apply-conf.sh
> +  $(basename "$0") apply-conf [<options>]
I made it non-optional and return an error if $# == 0