VOSA-616: Fix ece create-publication
escenic/ece-scripts pull request #82
Opened 2019-05-30 06:46 UTC by modhassan

Adjust publication creation form field change
publisherName --> publisherUUID

2019-05-31 08:49 UTC, skybert requested changes

2019-05-31 08:49 UTC, skybert commented on usr/share/escenic/ece-scripts/ece.d/create-publication.sh
> +  local url=http://localhost:8080/escenic-admin/pages/ou/list.jsp
Use the variable `${appserver_port}` instead of `8080`

2019-05-31 08:49 UTC, skybert commented on usr/share/escenic/ece-scripts/ece.d/create-publication.sh
> +function _create_publication_get_ou_uuid_by_publisher_name() {
The doc says the first argument is publisher name, but `$1` is not read in the function. The method instead assumes `pubisher_name` has been set by the caller.

Suggestion: Add:
```
local publisher_name=$1
```

To the beginning of the method and pass the publisher name in the caller.

2019-05-31 08:49 UTC, skybert commented on usr/share/escenic/ece-scripts/ece.d/create-publication.sh
> +  done <<< "$existing_ous"
Did you consider just piping the existing OUs:
```
_create_publication_get_existing_organizational_units |
  while read -r ou; do
     :
  done

```
?

2019-05-31 08:49 UTC, skybert commented on usr/share/escenic/ece-scripts/ece.d/create-publication.sh
> +    false || handle_error "Unable to find OU with name '$publisher_name'."
I don't get this `if` test: if `ou_uuid` is empty, then call the `false` command and if `false` fails, call `handle_error`? Why not just:
```
if [ -z "${out_uuid}" ]; then 
  handle_error "Unable to find OU with name '$publisher_name'."
fi
```
?

2019-05-31 08:49 UTC, skybert commented on usr/share/escenic/ece-scripts/ece.d/create-publication.sh
> +  curl --silent --fail --show-error "$url" | sed -n /'data-ou='/s,".*data-ou=[\"']\\([^\"']*\\)[\"'].*",'\1',p
Consider wrapping after `|` for increased readability.

2019-06-03 08:15 UTC, modhassan commented
@skybert Thanks for your valuable reviews.
I have adjusted PR accordingly on my last commit 624b5bc
Could you please check again?

2019-06-03 09:53 UTC, skybert commented
Looks very nice now, @modhassan . 

Remember to squash the two commits before merging.

2019-06-03 11:13 UTC, mogsie commented on usr/share/escenic/ece-scripts/ece.d/create-publication.sh
> +  done <<< "$existing_ous"
I like this syntax as it doesn't create a subshell.

2019-06-03 11:15 UTC, mogsie commented on usr/share/escenic/ece-scripts/ece.d/create-publication.sh
> +  ou_uuid=$(_create_publication_get_ou_uuid_by_publisher_name "${publisher_name}")
This will fail in any version of ECE earlier than 7.4.  Do we need to consider backwards compatibility here?

2019-06-03 12:17 UTC, skybert commented on usr/share/escenic/ece-scripts/ece.d/create-publication.sh
> +  ou_uuid=$(_create_publication_get_ou_uuid_by_publisher_name "${publisher_name}")
Yes, at the very least, this should run on any 7.x.

2019-06-03 21:59 UTC, modhassan commented
@mogsie @skybert I have a new commit 2436237 to support older ECE versions
Could you please review it?

2019-06-04 07:21 UTC, skybert commented on usr/share/escenic/ece-scripts/ece.d/create-publication.sh
> +## Retrun publisher field value
You need a spell checker in your editor :wink: `Retrun` → `Return`.

2019-06-04 07:29 UTC, skybert approved these changes

2019-06-04 07:29 UTC, skybert commented on usr/share/escenic/ece-scripts/ece.d/create-publication.sh
> +        sed -n /'name='/s,".*name=[\"']\\([^\"']*\\)[\"'].*",'\1',p
Suggestion: If you pass `-r` to `sed`. you don't have to escape the grouping parenthesis:
```
        sed -r -n /'name='/s,".*name=[\"']\([^\"']*\)[\"'].*",'\1',p
```

Also, `sed` should be on the same column as the `grep` on the line above it.

And lastly, remember to squash your three commits into one before merging it. On that note, I strongly recommend using `fixup` commits as this makes it much easier:
```
$ git commit -a --fixup <original sha>
```

Once the PR has been approved you let `git` squash them for you with:
```
$ git rebase --interactive --autosquash <orignal sha>^
```

The `^` takes the commit before the original sha, which is what you need for the `rebase`.

2019-06-04 07:29 UTC, skybert commented on usr/share/escenic/ece-scripts/ece.d/create-publication.sh
> +  if ! [ -z "${publisher_field_name}" ]; then
Instead of testing for not empty, you can test for `is set`:
```
if [ -n "${publisher_field_name}" ]; then
```

2019-06-04 09:45 UTC, mogsie commented on usr/share/escenic/ece-scripts/ece.d/create-publication.sh
> +        sed -n /'name='/s,".*name=[\"']\\([^\"']*\\)[\"'].*",'\1',p
Last PR I did I did "squash and merge" — is that frowned upon?  I didn't get a separate merge commit, and I guess some metadata is lost (a "link" to the PR, if only in text format)...

2019-06-04 10:53 UTC, mogsie commented
I squashed the commits, they should be ready to merge now.

2019-06-04 11:17 UTC, skybert commented on usr/share/escenic/ece-scripts/ece.d/create-publication.sh
> +        sed -n /'name='/s,".*name=[\"']\\([^\"']*\\)[\"'].*",'\1',p
> Last PR I did I did "squash and merge" — is that frowned upon? 

Not by me, at least :-) The `fixup` approach shines when it comes to PRs review/feedback, though, as the commits you make after the you created PR are responses to feedback from reviewers (or other changes you yourself wanted) and thus mere amendments to your initial work on the PR.

>  didn't get a separate merge commit, and I guess some metadata is lost 

FYI: You don't get a merge commit with the `git rebase --autosquash` either, see https://fle.github.io/git-tip-keep-your-branch-clean-with-fixup-and-autosquash.html

You get the date of the original commit and not the date of when you (auto)`squash`ed them. I like to update the date of the `squash`ed aggregate commit with:
```
git commit --amend --no-edit --date "$(date)"
```

2019-06-04 15:08 UTC, merged

2019-06-04 18:53 UTC, modhassan commented
@mogsie Thanks a lot :)